version: "3.9"
services:
  mysql:
    container_name: mysql
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3307:3306'
    expose:
      - '3306'

volumes:
  mysql:
    driver: local

